name: Deploy Lambda Function

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'  # Use the appropriate Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure you have a requirements.txt if your function has dependencies

      - name: Package Lambda function
        run: |
          zip -r function.zip .  # Adjust if your code is in a subdirectory

      - name: Deploy Lambda function
        uses: aws-actions/aws-lambda-deploy@v1
        with:
          function-name: FetchResume  # The name of your Lambda function
          zip-file: function.zip
          aws-region: 'us-east-1'  # Replace with your AWS region
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
